site_name: pypi-command-line
site_url: https://wasi-master.github.io/pypi-command-line
repo_name: wasi-master/pypi-command-line
repo_url: https://github.com/wasi-master/pypi-command-line
nav:
  - Home: index.md
  - Installation: install.md
  - Usage: usage.md
  - Notes: notes.md
  - Smart Features: smart_features.md
  - Testimonials: testimonials.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - header.autohide
    - toc.integrate
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  favicon: assets/favicon.png

plugins:
  # - search:
  #   separator: '\s'

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.betterem
  - pymdownx.keys

  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

  - toc:
      permalink: true

extra_javascript:
  - js/gif_script.js

extra_css:
  - css/custom.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wasi-master
copyright: Copyright &copy; 2021 Arian Mollik Wasi

edit_uri: ""
